config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
   }
  root   'static_pages#home'
  get    '/help',  to: 'static_pages#help'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/change_password', to: 'devise/registrations#edit'

  devise_scope :user do
    get    '/login',   to: 'devise/sessions#new'
    post   '/login',   to: 'devise/sessions#create'
    delete '/logout',  to: 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :index, :edit, :update]
  resources :projects
  resources :punches
  post 'punch_out', to: 'punches#punch_out', as: :punch_out

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_project_info.html.erb
<div class="container text-center">
  <h1><%= link_to @project.name, project_path(@project), class: "project-link" %></h1>
  <div class="col-6">
    <div class="col-12">
      <span><%= @pretty_time %></span>
    </div>
    <div class="col-12">
      <span><%= @project.description %></span>
    </div>
  </div>
</div>

app/views/shared/_project_list.html.erb
<div class="col-12">
  <h3>Projects (<%= @projects.count %>)</h3>
  <div class="list-group">
  <% @projects.each do |project| %>
      <%= link_to project_path(project), class: "list-group-item clickable-text" do %>
        <h2 class="h2"><small> <%= project.name %></small></h2>
     <% end %>
  <% end %>
  </div>
  <%= will_paginate @projects, previous_label: '<', next_label: '>' %>
</div>

app/views/shared/_punch_in_form.html.erb
<div class="col-12 text-center">
  <%= button_to punches_path(project_id: @project, method: :post), class:"btn btn-success btn-circle btn-xl", id: "punch-in" do %>
  <i class="fa fa-hourglass-start"></i>
  <% end %>
</div>

app/views/shared/_punch_out_form.html.erb
<div class="col-12 text-center">
  <%= button_to punch_out_path(id: @punch, method: :put), class:"btn btn-danger btn-circle btn-xl", id: "punch-out" do %>
  <i class="fa fa-hourglass-end"></i>
  <% end %>
</div>

app/views/shared/_timer.html.erb
<%= react_component("Timer", props: @timer_props, prerender: false) %>