config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
   }
  root   'static_pages#home'
  get    '/help',  to: 'static_pages#help'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/change_password', to: 'devise/registrations#edit'

  devise_scope :user do
    get    '/login',   to: 'devise/sessions#new'
    post   '/login',   to: 'devise/sessions#create'
    delete '/logout',  to: 'devise/sessions#destroy'
  end
  resources :users, only: [:show, :index, :edit, :update]
  resources :projects
  resources :punches
  post 'punch_out', to: 'punches#punch_out', as: :punch_out

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :punches, dependent: :destroy
  default_scope -> { order(last_punch: :desc) }
  validates :name, presence: true, uniqueness: {scope: :user_id}
  validates :description, presence: true

  # Checks the punch card for the most recent punch.
  # Not altering if there are no punches.
  def check_card
    if self.punches.first
      self.last_punch = self.punches.first.time_out || self.punches.first.time_in
      self.save
    end
  end

  def tally_cards
    sum = 0
    self.punches.each do |c|
      sum += c.time_worked
    end
    self.update(time_worked: sum)
  end

  def to_csv
    attributes = %w{id time_in time_out comment}

    ::CSV.generate(headers: true) do |csv|
      csv << attributes

      self.punches.each do |punch|
        csv << attributes.map{ |attr| punch.send(attr) }
      end
    end
  end
end

app/controllers/projects_controller.rb
require 'csv'

class ProjectsController < ApplicationController
  before_action :project_params,  only: [:update, :create]
  before_action :set_project,  only: [:show, :edit, :update]

  def show
    @ready = true
    @pretty_time = pretty_time(@project.time_worked)
    @rate = "15.00"
    if @project.punches.first
      @ready = !@project.punches.first.active?
      @rate = '%.2f' % ( @project.estimate / (@project.time_worked / 60 / 60) )
    end
    @punches = @project.punches.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.csv {
        send_data @project.to_csv,
        filename: "#{@project.name.parameterize.underscore}.csv"
      }
    end
  end

  def index
    @project  = current_user.projects.build
    @projects = current_user.projects.paginate(page: params[:page], per_page: 10)
  end

  def create
    @project = current_user.projects.build(project_params)
    @project.estimate.nil? ? @project.estimate = 0 : nil
    if @project.save
      flash[:success] = "Project created!"
      redirect_to project_path(@project)
    else
      flash[:error] = "Please enter a name"
      redirect_to user_path(current_user)
    end
  end

  def edit
    @pretty_time = pretty_time(@project.time_worked)
  end

  def update
    if @project.update_attributes(project_params)
      @project.check_card
      flash[:success] = "Project updated"
      redirect_to project_path @project
    else
      render 'edit'
    end

  end

  private

    def project_params
      params.require(:project).permit(:name, :description, :estimate)
    end

    def set_project
      @project = Project.find(params[:id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :name, placeholder: "Name your next project..." %>
  </div>
  <div class="field">
    <%= f.text_area :description, placeholder: "Add a description" %>
  </div>
  <div class="field">
    <%= f.text_field :estimate, placeholder: "Estimated income" %>
  </div>
  <% if @project.id %>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% else %>
    <%= f.submit "Create", class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/projects/_project_info.html.erb
<div class="container text-center">
  <h1><%= link_to @project.name, project_path(@project), class: "project-link" %></h1>
  <div class="col-6">
    <div class="col-12">
      <div class="clock-screen">
        <span><%= @pretty_time %></span>
      </div>
    </div>
    <div class="col-12">
      <span><%= @project.description %></span>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="col-11">
  <section class="project_info">
    <%= render 'project_info' %>
  </section>
  <section class="project_form">
    <%= render 'project_form' %>
  </section>
</div>

app/views/projects/edit_project.html.erb
<div>
  <section class="project_info">
  <%= render 'project_info' %>
  </section>
  <section class="project_form">
    <%= render 'project_form' %>
  </section>
</div>

app/views/projects/index.html.erb
<% provide(:title, "Projects") %>
<h1><%= current_user.nickname %>'s Projects</h1>

<div class="col-11">
  <section class="project_form">
    <%= render 'project_form' %>
  </section>
  <section class="project_form">
    <%= render 'shared/project_list' %>
  </section>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>
<div class="row text-center">
  <section class="project_info">
    <%= render 'project_info' %>
  </section>
  <% if @ready %>
    <section class="punch_in_form">
      <%= render 'shared/punch_in_form' %>
    </section>
  <% end %>
  <div>
    <%= link_to 'edit', edit_project_path %>
  </div>
  <div class="col-12">
    <h3><%= "Estimate: $#{'%.2f' %  @project.estimate}" %></h3>
  </div>
  <div class="col-12">
    <h3><%= "Rate: $#{@rate} / hr" %></h3>
  </div>
  <div class="container">
    <% if @punches.any? %>
      <%= will_paginate @punches, previous_label: '<', next_label: '>' %>

      <div class="list-group">
        <%= render @punches %>
      </div>

      <%= will_paginate @punches, previous_label: '<', next_label: '>' %>
    <% end %>
  </div>
  <p>
    Download Punch Card:
    <%= link_to "CSV", project_path(format: "csv") %>
  </p>
</div>